# Generated by Django 5.0 on 2023-12-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='stat',
            new_name='state',
        ),
    ]
